var searchData=
[
  ['xeventgroupdefinition_0',['xEventGroupDefinition',['../structx_event_group_definition.html',1,'']]],
  ['xlist_1',['xLIST',['../structx_l_i_s_t.html',1,'']]],
  ['xlist_5fitem_2',['xLIST_ITEM',['../structx_l_i_s_t___i_t_e_m.html',1,'']]],
  ['xmemory_5fregion_3',['xMEMORY_REGION',['../structx_m_e_m_o_r_y___r_e_g_i_o_n.html',1,'']]],
  ['xmini_5flist_5fitem_4',['xMINI_LIST_ITEM',['../structx_m_i_n_i___l_i_s_t___i_t_e_m.html',1,'']]],
  ['xpsr_5ftype_5',['xPSR_Type',['../unionx_p_s_r___type.html',1,'']]],
  ['xstatic_5fevent_5fgroup_6',['xSTATIC_EVENT_GROUP',['../structx_s_t_a_t_i_c___e_v_e_n_t___g_r_o_u_p.html',1,'']]],
  ['xstatic_5flist_7',['xSTATIC_LIST',['../structx_s_t_a_t_i_c___l_i_s_t.html',1,'']]],
  ['xstatic_5flist_5fitem_8',['xSTATIC_LIST_ITEM',['../structx_s_t_a_t_i_c___l_i_s_t___i_t_e_m.html',1,'']]],
  ['xstatic_5fmini_5flist_5fitem_9',['xSTATIC_MINI_LIST_ITEM',['../structx_s_t_a_t_i_c___m_i_n_i___l_i_s_t___i_t_e_m.html',1,'']]],
  ['xstatic_5fqueue_10',['xSTATIC_QUEUE',['../structx_s_t_a_t_i_c___q_u_e_u_e.html',1,'']]],
  ['xstatic_5fstream_5fbuffer_11',['xSTATIC_STREAM_BUFFER',['../structx_s_t_a_t_i_c___s_t_r_e_a_m___b_u_f_f_e_r.html',1,'']]],
  ['xstatic_5ftcb_12',['xSTATIC_TCB',['../structx_s_t_a_t_i_c___t_c_b.html',1,'']]],
  ['xstatic_5ftimer_13',['xSTATIC_TIMER',['../structx_s_t_a_t_i_c___t_i_m_e_r.html',1,'']]],
  ['xstream_5fbuffer_14',['xSTREAM_BUFFER',['../structx_s_t_r_e_a_m___b_u_f_f_e_r.html',1,'']]],
  ['xtask_5fparameters_15',['xTASK_PARAMETERS',['../structx_t_a_s_k___p_a_r_a_m_e_t_e_r_s.html',1,'']]],
  ['xtask_5fstatus_16',['xTASK_STATUS',['../structx_t_a_s_k___s_t_a_t_u_s.html',1,'']]],
  ['xtime_5fout_17',['xTIME_OUT',['../structx_t_i_m_e___o_u_t.html',1,'']]]
];
