var searchData=
[
  ['pctaskgethandle_0',['pcTaskGetHandle',['../group__pc_task_get_handle.html',1,'']]],
  ['pctaskgetname_1',['pcTaskGetName',['../group__pc_task_get_name.html',1,'']]],
  ['peripheral_20access_20controller_2',['Peripheral Access Controller',['../group___s_a_m_d20___p_a_c.html',1,'']]],
  ['peripheral_20base_20address_20definitions_3',['Peripheral Base Address Definitions',['../group___s_a_m_d20_e14__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e14_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e15__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e15_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e16__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e16_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e17__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e18__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g14__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g14_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g15__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g15_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g16__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g16_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g17__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g17_u__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g18__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g18_u__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j14__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j14_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j15__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j15_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j16__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j16_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j17__base.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j18__base.html',1,'(Global Namespace)']]],
  ['peripheral_20ids_20definitions_4',['Peripheral Ids Definitions',['../group___s_a_m_d20_e14__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e14_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e15__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e15_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e16__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e16_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e17__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e18__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g14__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g14_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g15__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g15_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g16__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g16_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g17__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g17_u__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g18__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g18_u__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j14__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j14_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j15__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j15_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j16__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j16_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j17__id.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j18__id.html',1,'(Global Namespace)']]],
  ['peripheral_20software_20api_5',['Peripheral Software API',['../group__fuses__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e14__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e14_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e15__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e15_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e16__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e16_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e17__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e18__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g14__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g14_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g15__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g15_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g16__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g16_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g17__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g17_u__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g18__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g18_u__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j14__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j14_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j15__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j15_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j16__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j16_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j17__api.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j18__api.html',1,'(Global Namespace)']]],
  ['pid_20motor_20control_6',['PID Motor Control',['../group___p_i_d.html',1,'']]],
  ['port_20definitions_7',['PORT Definitions',['../group___s_a_m_d20_e14__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e14_b__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e15__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e15_b__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e16__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e16_b__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e17__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_e18__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g14__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g14_b__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g15__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g15_b__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g16__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g16_b__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g17__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g17_u__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g18__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_g18_u__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j14__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j14_b__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j15__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j15_b__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j16__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j16_b__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j17__port.html',1,'(Global Namespace)'],['../group___s_a_m_d20_j18__port.html',1,'(Global Namespace)']]],
  ['port_20module_8',['Port Module',['../group___s_a_m_d20___p_o_r_t.html',1,'']]],
  ['power_20manager_9',['Power Manager',['../group___s_a_m_d20___p_m.html',1,'']]],
  ['preprocessor_20_2d_20macro_20recursion_10',['Preprocessor - Macro Recursion',['../group__group__sam0__utils__mrecursion.html',1,'']]],
  ['preprocessor_20_2d_20macro_20repeat_11',['Preprocessor - Macro Repeat',['../group__group__sam0__utils__mrepeat.html',1,'']]],
  ['preprocessor_20_2d_20stringize_12',['Preprocessor - Stringize',['../group__group__sam0__utils__stringz.html',1,'']]],
  ['preprocessor_20_2d_20token_20paste_13',['Preprocessor - Token Paste',['../group__group__sam0__utils__tpaste.html',1,'']]]
];
